server:
  port: 9001

eureka:
  client:
    register-with-eureka: true #是否将自己注册到注册中心上
    fetch-registry: true #是否从Eureka上获取注册信息
    service-url: # EurekaServer地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
spring:
  cloud:
    gateway:
      routes:
        - id: user_service_route
          uri: lb://axx-user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: book_service_route
          uri: lb://axx-book-service
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix=2
  application:
    name: gateway

